### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_1(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_11 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_11__Ljava_lang_String_2)

### ISSUE THREAD

**Issue by yeshiyuan00** [AndroidEx-SDK/FaceCard#1]
运行ASM时出现下面的错误信息：
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.objdetect.CascadeClassifier.CascadeClassifier_1(java.lang.String) (tried Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_11 and Java_org_opencv_objdetect_CascadeClassifier_CascadeClassifier_11__Ljava_lang_String_2)
                                                                   at org.opencv.objdetect.CascadeClassifier.CascadeClassifier_1(Native Method)
                                                                   at org.opencv.objdetect.CascadeClassifier.<init>(CascadeClassifier.java:58)
                                                                   at com.example.asm.ImageUtils.initCascade(ImageUtils.java:153)
                                                                   at com.example.asm.ImageUtils.access$000(ImageUtils.java:35)
                                                                   at com.example.asm.ImageUtils$1.run(ImageUtils.java:47)
06

**Comment by clubedosign** [comment]
hello man, did you manage to solve this error ?? could send me? renato-muniz@hotmail.com
 tks
